#1 Prepare
- name: Create Ghost User
  user:
    name: ghost
    shell: /usr/sbin/nologin
    
- name: Create Ghost directory
  file:
    path: /data/wwwroot/ghost
    state: directory
    owner: ghost
    group: ghost

#2 Install
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Copy docker-compose.yml and config.production.json
  template:
    src: "{{item}}"
    dest: /data/wwwroot/ghost/{{item}}
  loop:
    - docker-compose.yml
    - config.production.json

- name: Run docker-compose
  shell: |
    docker-compose up -d 
    sleep 30s
  args:
    chdir: /data/wwwroot/ghost

#3 Configure
- name: Permission settings and need restart docker
  shell: |
    chown -R ghost.ghost /data/wwwroot/ghost
    find /data/wwwroot/ghost -type d -exec chmod 750 {} \;
    find /data/wwwroot/ghost -not -type d -exec chmod 640 {} \;
    chmod 0644 /data/wwwroot/ghost/config.production.json
    docker restart ghost

#4 Verify
- name: Check Ghost Version
  shell: |
    sudo echo -e "node_version: `docker exec -it ghost /bin/bash -c 'node -v'`" |sudo tee -a /data/logs/install_version.txt
    sudo echo -e "ghost_version: `docker exec -it ghost /bin/bash -c 'ls versions'`" |sudo tee -a /data/logs/install_version.txt
